FROM node:16-alpine

WORKDIR /app

# Only copy package.json first for caching layer
COPY package*.json ./

RUN npm install

# Now copy the rest of the app
COPY . .

# Set environment explicitly
ENV CI=true

# Use this CMD to run tests once in CI
CMD ["npm", "run", "test", "--", "--watchAll=false"]
