language: generic
sudo: required
services:
 - docker

before_install:
 - docker run -e CI=true gooferbyte/react-test npm test


scripts:
 - docker run gooferbyte/react-test npm test -- --coverage

after_success:
 - docker build -t gooferbyte/multi-client ./client
 - docker build -t gooferbyte/multi-nginx ./nginx
 - docker build -t gooferbyte/multi-server ./server
 - docker build -t gooferbyte/multi-worker ./worker
