name: Multi-Container CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image and run tests
        run: |
          docker build -t gooferbyte/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true gooferbyte/react-test npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t gooferbyte/multi-client ./client
          docker build -t gooferbyte/multi-nginx ./nginx
          docker build -t gooferbyte/multi-server ./server
          docker build -t gooferbyte/multi-worker ./worker

      - name: Push Docker images
        run: |
          docker push gooferbyte/multi-client
          docker push gooferbyte/multi-nginx
          docker push gooferbyte/multi-server
          docker push gooferbyte/multi-worker
