name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        run: docker build -t react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests (CI=true)
        run: docker run -e CI=true react-test npm test

      - name: Run tests with coverage
        run: docker run react-test npm test -- --coverage

  build-images:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build client image
        run: docker build -t gooferbyte/multi-client ./client

      - name: Build nginx image
        run: docker build -t gooferbyte/multi-nginx ./nginx

      - name: Build server image
        run: docker build -t gooferbyte/multi-server ./server

      - name: Build worker image
        run: docker build -t gooferbyte/multi-worker ./worker
